services:
  - type: web
    name: floracore
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn invernadero.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
