services:
  - type: web
    name: floracore
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn invernadero.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "invernadero.settings"
