# Generated by Django 5.1.1 on 2025-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hume', models.CharField(max_length=20)),
                ('hume_floor', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
            ],
        ),
    ]
