# Generated by Django 4.1.7 on 2025-04-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_grenhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grenhouse',
            name='id_parameters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parameters'),
        ),
    ]
