# Generated by Django 5.1.1 on 2025-05-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_grenhouse_id_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='light',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
