# Generated by Django 5.2.6 on 2025-09-29 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_parameters_light"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_threshold", models.FloatField(default=28.0)),
                ("hume_floor_threshold", models.FloatField(default=40.0)),
                ("light_threshold", models.FloatField(default=500.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name="parameters",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="parameters",
            name="riego",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parameters",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="parameters",
            name="ventiladores",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="hume",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="hume_floor",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="light",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="temperature",
            field=models.FloatField(),
        ),
    ]
