# Generated by Django 5.1.1 on 2025-10-12 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parameters_light'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(default=20.0)),
                ('temp_max', models.FloatField(default=25.0)),
                ('hum_min', models.FloatField(default=60.0)),
                ('hum_max', models.FloatField(default=80.0)),
                ('light_hours', models.IntegerField(default=12)),
                ('auto_watering', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
