# Generated by Django 5.1.1 on 2025-10-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_parameters_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameters",
            name="foco",
            field=models.BooleanField(default=False),
        ),
    ]
