@echo off
echo [INFO] Iniciando FloraCore de forma segura...

echo [INFO] Verificando base de datos...
python fix_user_persistence.py

echo [INFO] Aplicando migraciones si es necesario...
python manage.py migrate

echo [INFO] Iniciando servidor...
python manage.py runserver